name: Deploy to ECS (EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::472188560076:role/github-pipeline
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image to ECR
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t 472188560076.dkr.ecr.us-west-2.amazonaws.com/mi-nestjs-app:$IMAGE_TAG .
        docker push 472188560076.dkr.ecr.us-west-2.amazonaws.com/mi-nestjs-app:$IMAGE_TAG
        echo "IMAGE_TAG?$IMAGE_TAG" >> $GITHUB_ENV

    - name: Render ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        container-name: mi-nestjs-app
        image: 472188560076.dkr.ecr.us-west-2.amazonaws.com/mi-nestjs-app:${{ env.IMAGE_TAG }}

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: mi-nestjs-task-service-61kboknd
        cluster: nest-apps-cluster
        wait-for-service-stability: true
